### ISSUE TITLE
Data locality Features

### ISSUE THREAD

**Issue by slimshady986** [gluster/gluster-kubernetes#201]
Hello,

I was wondering if its possible with Kubernetes+heketi to provision gluster volumes on the same node where a  pod has be deployed to improve performances of data transfer . I don't know if heketi placement logic is already doing this kind of optimization out of the box.

Thanks in advance and sorry if its not the place to ask the question

**Comment by obnoxxx** [comment]
Hi @slimshady986 thanks for using the software and providing feed-back! Not need to apologize: This is exactly the right place!

Currently, heketi is completely unaware of how the volumes it creates are later used, hence no logic is in place.

I also doubt that it will be (easily) doable to implement such a logic, since in kubernetes a persistent volume (with ReadWriteMany access-mode) can be mounted from many pods. Even if it is only ever mounted by a single pod, that pod could move to different nodes in the cluster, so unless a pod is pinned to node, I don't see how we could optimize at all...

**Comment by slimshady986** [comment]
Thanks Michael @obnoxxx for you quick answer,

All in all, I rather see this kind of optimization implemented on the kubernetes side. I can imagine something like the volume plugin (or storage class) propagating these kind of infos (when possible) to apiserver and used by the scheduler as a soft requirement to place pod (with load balancing to all replicas).

I ll post again this question to Kubernetes guys if this kind of things are on their roadmap
