### ISSUE TITLE
Is it possible to configure gluster in distributed mode?

### ISSUE THREAD

**Issue by alvarosIGZ** [gluster/gluster-kubernetes#420]
Hello,
According to this guide: http://docs.gluster.org/en/latest/Quick-Start-Guide/Architecture/

I've seen that when you configure glusterfs in Kubernetes is configured in replicated mode, but... is it possible to configure it in distributed mode? In that way, when I deploy my gluster volumes (PVC, PV and so) I have a distributed volume.

Thanks,

**Comment by jarrpa** [comment]
A distributed volume is the "default" GlusterFS volume type. Volumes with replica > 1 are called distributed-replica volumes. So, if you set replica=1 you effectively have a distributed volume. There are two ways you can achieve this:

1. Use heketi-cli to create a volume using the option `-durability none`
2. Create a StorageClass that sets `volumetype: none` as a parameter

If either or both of these work for you, please let us know and close this Issue. Otherwise, we'll be here. :)

**Comment by alvarosIGZ** [comment]
Hello!
I've tried the second solution and it works like a charm!
Thanks for the reply! :) You can close the issue now.

**Comment by jarrpa** [comment]
Good to hear!
