### ISSUE TITLE
Heketi endpoint is changing after each reboot

### ISSUE THREAD

**Issue by xelfe** [gluster/gluster-kubernetes#426]
I'm using the heketi endpoint like the docs say for the resturl of the storage class but this endpoint change after all reboot so I have to change the storageclass each time. there's any way to prevent this ?

**Comment by jarrpa** [comment]
The service endpoint IP is not guaranteed to be static. IPs in Kube are generally not guaranteed to be static. For that you want to use DNS names, and all services are given a cluster-internal name, something like `heketi.svc.local.example.com`. Note that since the GlusterFS provisioner needs to be able to talk to the heketi service, this name must also be resolvable outside the Kube cluster.

**Comment by xelfe** [comment]
> The service endpoint IP is not guaranteed to be static. IPs in Kube are generally not guaranteed to be static. For that you want to use DNS names, and all services are given a cluster-internal name, something like heketi.svc.local.example.com. Note that since the GlusterFS provisioner needs to be able to talk to the heketi service, this name must also be resolvable outside the Kube cluster.

@jarrpa so I should use ingress on that ? You say it must be resolvable outside the kube cluster but actually it's dont and it's work. For security reason it's not suppose to be all internal ?

**Comment by jarrpa** [comment]
Sorry, by outside the kube cluster I meant outside the cluster internal network. Specifically, the GlusterFS provisioner operates outside the networking fabric that Kube creates for pod-to-pod communication, and thus there are some configurations where the provisioner would not be able to resolve cluster-internal names. Since it works for you, that's properly configured. :) Does that resolve your issue?

**Comment by xelfe** [comment]
yes thank you @jarrpa
