### ISSUE TITLE
Can I define the number of replicas  in pvc?

### ISSUE THREAD

**Issue by dotbalo** [gluster/gluster-kubernetes#543]
Can I define a different  number of replica in different pvcs？

**Comment by dotbalo** [comment]
ok, thank you so much.
I can create three different StorageClasses, respectively defining the volumetype's replicate as 1, 2, 3.

**Comment by phlogistonjohn** [comment]
That error indicates that heketi tried to create volumes, the create failed, and then heketi also failed to remove any components left over from the failed create.
We'll need heketi logs to debug any further.

**Comment by phlogistonjohn** [comment]
Hi there, a screenshot of a small section of the logs is not sufficient to determine what the issue was.
I recommend doing something like `kubectl logs -f <heketi-pod-id> | tee heketi.logs.txt` and then reproducing the problem while tailing the logs. Once you've captured logging from while the error occured, put the logs somewhere (http://fpaste.org for example) that we can view it.

**Comment by dotbalo** [comment]
@phlogistonjohn  Hi, thanks for your reply, I executed the command you said, and saved [heketi.logs.txt](https://paste.fedoraproject.org/paste/ZjTJ-25EfIllJTfDVyqQ5A) , then I found this error: "replica count should be greater than 1" in this file, then I changed the "replicate:1" to "replicate:2",finally the PVC is OK, So the reason for this problem is that glusterfs does not allow the creation of a pv with a replica of 1. Thank you so much, @nixpanic @phlogistonjohn
