### ISSUE TITLE
Problem with service URI

### ISSUE THREAD

**Issue by ap1969** [gluster/gluster-kubernetes#596]
Sorry,
I'm not familiar with how to suggest updates to projects, but there's an issue in the gk-deploy, where the heteki service URL is determined by then not used:

Line 830: replace "localhost:8080" with ${heketi_service}

Hope that helps,
Andy

**Comment by phlogistonjohn** [comment]
Thanks for the suggestion, however I tihnk that line ought to work because its being executed within the heketi pod itself. Note the part `{CLI} exec -i ${heketi_pod}` that comes before the heketi-cli section.
Were the heketi-cli commands that are supposed to run within the pod failing for you? If so, what was the exact error(s) that you received?

**Comment by ap1969** [comment]
Hi John
Thanks for getting back. Unfortunately I'm the meantime I've been testing with Ceph and got that working, so I can't remember what I was doing with gluster.

**Comment by phlogistonjohn** [comment]
Shall we close this issue then? If you hit it again you can always reopen.

**Comment by ap1969** [comment]
Done.
