### ISSUE TITLE
Gluster volume not deleted if StorageClass uses Reclaim Policy "Retain"

### ISSUE THREAD

**Issue by Retrospector** [gluster/gluster-kubernetes#600]
Hi,
I noticed this while searching for the reason why Heketi is not deleting the Gluster volumes after the PV is deleted in Kubernetes. 
The "Retain" Reclaim Policy should keep the PV around after the PVClaim is deleted. But when I then manually delete the Released PV, the backing Gluster volume stays. I'd expected that Heketi would delete the Volume if a released PV is maually deleted.

Is this expected behavior?
Thanks in advance for your assistance.

**Comment by phlogistonjohn** [comment]
Heketi has to be "told" to delete a volume and that happens within the provisioner. If the provisioner does not send a delete api request to heketi when the PV is deleted without a PVC present then this sounds like the behavior I'd expect. That makes sense because the PVC is what links the PV to the provisioning mechanism.

I somewhat doubt this can be changed but if you want to discuss it further that would probably be best upstream in kubernetes where the provisioner is implemented.

**Comment by Retrospector** [comment]
So, a lack of knowledge about kubernetes on my part.
Thank you, I appreaciate the quick response.
